# Generated by Django 5.1.6 on 2025-08-14 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cad_contrato", "0002_alter_regional_unique_together"),
        ("cadastro_equipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipamentoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("DESPESAS_TI", "Despesas TI"),
                            ("MATERIAIS_CONSUMO", "Materiais de Consumo"),
                            ("DESPESAS_DIVERSAS", "Despesas Diversas"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "valor_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Mensal (R$)",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamentos_mensais",
                        to="cad_contrato.cadastrocontrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento/Despesa Mensal",
                "verbose_name_plural": "Equipamentos/Despesas Mensais",
                "ordering": ["categoria", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="EquipamentoVidaUtil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("EPI", "EPI - Equipamentos de Proteção Individual"),
                            ("EPC", "EPC - Equipamentos de Proteção Coletiva"),
                            ("FERRAMENTAS", "Ferramentas"),
                            ("EQUIPAMENTOS_TI", "Equipamentos TI"),
                        ],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "vida_util_meses",
                    models.PositiveIntegerField(verbose_name="Vida Útil (meses)"),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor Unitário (R$)",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamentos_vida_util",
                        to="cad_contrato.cadastrocontrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento com Vida Útil",
                "verbose_name_plural": "Equipamentos com Vida Útil",
                "ordering": ["categoria", "descricao"],
            },
        ),
        migrations.CreateModel(
            name="EquipamentoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_por_equipe",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade por Equipe"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipamentos_vinculados",
                        to="cadastro_equipe.equipe",
                        verbose_name="Equipe",
                    ),
                ),
                (
                    "equipamento_mensal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculacoes_equipe",
                        to="equipamentos.equipamentomensal",
                    ),
                ),
                (
                    "equipamento_vida_util",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculacoes_equipe",
                        to="equipamentos.equipamentovidautil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipamento por Equipe",
                "verbose_name_plural": "Equipamentos por Equipe",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("equipamento_vida_util__isnull", False)),
                        fields=("equipamento_vida_util", "equipe"),
                        name="unique_vida_util_equipe",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("equipamento_mensal__isnull", False)),
                        fields=("equipamento_mensal", "equipe"),
                        name="unique_mensal_equipe",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("equipamento_mensal__isnull", True),
                                ("equipamento_vida_util__isnull", False),
                            ),
                            models.Q(
                                ("equipamento_mensal__isnull", False),
                                ("equipamento_vida_util__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="equipamento_equipe_only_one_type",
                    ),
                ],
            },
        ),
    ]
