# Generated by Django 5.1.6 on 2025-08-14 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0002_alter_regional_unique_together"),
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipamentoequipe",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipamentos_equipe",
                to="cad_contrato.cadastrocontrato",
                verbose_name="Contrato",
            ),
        ),
    ]
