# Generated by Django 5.1.6 on 2025-02-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractconfiguration",
            old_name="cidade",
            new_name="municipio",
        ),
    ]
