# Generated by Django 5.1.6 on 2025-04-06 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cad_contrato", "0002_alter_cadastrocontrato_status_contrato"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiosColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assistencia_medica_odonto",
                    models.DecimalField(
                        decimal_places=2,
                        default=151.0,
                        max_digits=7,
                        verbose_name="Assistência médica odontológica",
                    ),
                ),
                (
                    "exames_periodicos",
                    models.DecimalField(
                        decimal_places=2,
                        default=109.0,
                        max_digits=7,
                        verbose_name="Exames periódicos (um por ano)",
                    ),
                ),
                (
                    "refeicao",
                    models.DecimalField(
                        decimal_places=2,
                        default=398.0,
                        max_digits=7,
                        verbose_name="Refeição",
                    ),
                ),
                (
                    "transporte",
                    models.DecimalField(
                        decimal_places=2,
                        default=278.0,
                        max_digits=7,
                        verbose_name="Transporte",
                    ),
                ),
                (
                    "outros_custos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=7,
                        verbose_name="Outros Custos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=7, verbose_name="Total"
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalcGrupoAEncargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cpp",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="CPP (Contribuição Previdenciária Patronal)",
                    ),
                ),
                (
                    "cpp_fgts_sal_abono",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="(CPP + FGTS) x (13 salário + abono de férias)",
                    ),
                ),
                (
                    "total_grupo_a",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Grupo A",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalcGrupoBIndenizacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ed",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="Demissões = ED",
                    ),
                ),
                (
                    "me",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="Meses no emprego = ME",
                    ),
                ),
                (
                    "percentual_multa_fgts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Percentual multa do FGTS",
                    ),
                ),
                (
                    "multa_fgts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        verbose_name="Multa do FGTS",
                    ),
                ),
                (
                    "aviso_previo_indenizado",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Aviso prévio indenizado",
                    ),
                ),
                (
                    "fgts_sobre_aviso_previo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="FGTS sobre aviso prévio indenizado",
                    ),
                ),
                (
                    "total_grupo_b",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Grupo B",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalcGrupoCSubstituicoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horas_trab_ano",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas trabalhas no ano",
                    ),
                ),
                (
                    "semanas_ferias",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Semanas de férias = 30 ÷ 7",
                    ),
                ),
                (
                    "horas_ausencia_ferias",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas de ausência nas férias (HAF = HTS x SF - HFF)",
                    ),
                ),
                (
                    "dias_faltas_ano",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Dias de faltas no ano",
                    ),
                ),
                (
                    "horas_trab_semana",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas trabalhadas na semana",
                    ),
                ),
                (
                    "horas_feriados_ferias",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas de feriados nas férias",
                    ),
                ),
                (
                    "horas_trab_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas trabalhadas no dia",
                    ),
                ),
                (
                    "horas_faltas_justificadas_ano",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Horas de faltas justificadas no ano (HFJA = HAF + DF x HTD)",
                    ),
                ),
                (
                    "total_grupo_c",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Grupo C",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalcGrupoD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_grupo_d",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Grupo D",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalcGrupoE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_grupo_e",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Total Grupo E",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrupoAEncargos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inss",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="INSS (%)",
                    ),
                ),
                (
                    "incra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.2,
                        max_digits=5,
                        verbose_name="INCRA (%)",
                    ),
                ),
                (
                    "sebrae",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.6,
                        max_digits=5,
                        verbose_name="SEBRAE (%)",
                    ),
                ),
                (
                    "senai",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="SENAI (%)",
                    ),
                ),
                (
                    "sesi",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.5,
                        max_digits=5,
                        verbose_name="SESI (%)",
                    ),
                ),
                (
                    "sal_educacao",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.5,
                        max_digits=10,
                        verbose_name="Salário Educação (%)",
                    ),
                ),
                (
                    "rat",
                    models.DecimalField(
                        choices=[(1.0, "1,0%"), (2.0, "2,0%"), (3.0, "3,0%")],
                        decimal_places=2,
                        default=3.0,
                        max_digits=5,
                        verbose_name="RAT (Riscos Ambientais do Trabalho)",
                    ),
                ),
                (
                    "fap",
                    models.DecimalField(
                        choices=[
                            (0.5, "0,5%"),
                            (1.0, "1,0%"),
                            (1.5, "1,5%"),
                            (2.0, "2,0%"),
                        ],
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="FAP (Fator Acidentário de Prevenção)",
                    ),
                ),
                (
                    "fgts",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        max_digits=5,
                        verbose_name="FGTS (%)",
                    ),
                ),
                (
                    "dec_salario",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.33,
                        max_digits=5,
                        verbose_name="13 Salário (R$)",
                    ),
                ),
                (
                    "abono_ferias",
                    models.DecimalField(
                        decimal_places=2,
                        default=2.78,
                        max_digits=5,
                        verbose_name="Abono de Férias (%)",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrupoBIndenizacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "demissoes",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        verbose_name="Demissões",
                    ),
                ),
                (
                    "meses_emprego",
                    models.IntegerField(default=36, verbose_name="Meses no emprego"),
                ),
                (
                    "multa_fgts",
                    models.DecimalField(
                        decimal_places=2,
                        default=40.0,
                        max_digits=5,
                        verbose_name="Percentual multa do FGTS",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrupoCSubstituicoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_reserva_tecnica",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        default="sim",
                        max_length=3,
                        verbose_name="A reserva técnica  já está sendo considerada?",
                    ),
                ),
                (
                    "hras_trab_semana",
                    models.IntegerField(
                        default=44, verbose_name="Horas trabalhadas na semana"
                    ),
                ),
                (
                    "dias_trabalho_semana",
                    models.IntegerField(
                        default=5, verbose_name="Dias de trabalho na semana"
                    ),
                ),
                (
                    "feriados_fixos",
                    models.IntegerField(
                        default=5,
                        verbose_name="Feriados fixos no ano - ocorrem sempre nos dias de trabalho",
                    ),
                ),
                (
                    "feriados_moveis",
                    models.IntegerField(
                        default=12,
                        verbose_name="Feriados móveis no ano - ocorrem em qualquer dia da semana",
                    ),
                ),
                (
                    "dias_falta_ano",
                    models.IntegerField(default=3, verbose_name="Dias de falta no ano"),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
    ]
