# Generated by Django 5.1.6 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mao_obra", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupoaencargos",
            name="fap",
            field=models.DecimalField(
                choices=[(0.5, "0,5"), (1.0, "1,0"), (1.5, "1,5"), (2.0, "2,0")],
                decimal_places=2,
                default=1.0,
                max_digits=5,
                verbose_name="FAP (Fator Acidentário de Prevenção)",
            ),
        ),
    ]
