# Generated by Django 5.1.6 on 2025-07-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mao_obra", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficioscolaborador",
            name="total",
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="alojamento",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="assistencia_medica_odonto",
            field=models.DecimalField(decimal_places=2, default=151.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="cesta_basica",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="dias_trabalhados_mes",
            field=models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="exames_periodicos",
            field=models.DecimalField(decimal_places=2, default=109.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="outros_custos",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="percentual_participacao_transporte",
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="previdencia_privada",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="refeicao",
            field=models.DecimalField(decimal_places=2, default=398.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="seguro_vida",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name="beneficioscolaborador",
            name="transporte",
            field=models.DecimalField(decimal_places=2, default=278.0, max_digits=7),
        ),
    ]
