# Generated by Django 5.1.6 on 2025-05-12 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
        ("mao_obra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EncargosSociaisCentralizados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_grupo_a",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Grupo A",
                    ),
                ),
                (
                    "total_grupo_b",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Grupo B",
                    ),
                ),
                (
                    "total_grupo_c",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Grupo C",
                    ),
                ),
                (
                    "total_grupo_d",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Grupo D",
                    ),
                ),
                (
                    "total_grupo_e",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Grupo E",
                    ),
                ),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encargos_centralizados",
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
    ]
