# Generated by Django 5.1.6 on 2025-08-16 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cad_contrato", "0002_alter_regional_unique_together"),
        ("cadastro_equipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Tipo"
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("veiculo_leve", "Veículo Leve"),
                            ("veiculo_pesado", "Veículo Pesado"),
                            ("implemento", "Implemento"),
                            ("equipamento", "Equipamento"),
                        ],
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                (
                    "especificacoes_tecnicas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Especificações Técnicas"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tipo de Veículo",
                "verbose_name_plural": "Tipos de Veículos",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_aquisicao",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Valor de Aquisição (R$)",
                    ),
                ),
                (
                    "vida_util_meses",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Vida Útil (meses)"
                    ),
                ),
                (
                    "custo_mensal_seguro",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Custo Mensal de Seguro (R$)",
                    ),
                ),
                (
                    "custo_mensal_manutencao",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Custo Mensal de Manutenção (R$)",
                    ),
                ),
                (
                    "tipo_combustivel",
                    models.CharField(
                        choices=[
                            ("gasolina", "Gasolina"),
                            ("etanol", "Etanol"),
                            ("diesel", "Diesel"),
                            ("flex", "Flex (Gasolina/Etanol)"),
                            ("gnv", "GNV"),
                            ("eletrico", "Elétrico"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Combustível",
                    ),
                ),
                (
                    "eficiencia_km_litro",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Eficiência (Km/L)"
                    ),
                ),
                (
                    "km_por_mes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=8,
                        verbose_name="Km por Mês",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="cad_contrato.cadastrocontrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "tipo_veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="veiculos",
                        to="veiculos.tipoveiculo",
                        verbose_name="Tipo de Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": [
                    "contrato",
                    "tipo_veiculo__categoria",
                    "tipo_veiculo__nome",
                ],
                "unique_together": {("contrato", "tipo_veiculo")},
            },
        ),
        migrations.CreateModel(
            name="PrecoCombustivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_combustivel",
                    models.CharField(
                        choices=[
                            ("gasolina", "Gasolina"),
                            ("etanol", "Etanol"),
                            ("diesel", "Diesel"),
                            ("flex", "Flex (Gasolina/Etanol)"),
                            ("gnv", "GNV"),
                            ("eletrico", "Elétrico"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Combustível",
                    ),
                ),
                (
                    "preco_por_litro",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        verbose_name="Preço por Litro (R$)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="precos_combustivel",
                        to="cad_contrato.cadastrocontrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preço de Combustível",
                "verbose_name_plural": "Preços de Combustível",
                "ordering": ["contrato", "tipo_combustivel"],
                "unique_together": {("contrato", "tipo_combustivel")},
            },
        ),
        migrations.CreateModel(
            name="AtribuicaoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes_veiculo",
                        to="cad_contrato.cadastrocontrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "escopo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes_veiculo",
                        to="cadastro_equipe.escopoatividade",
                        verbose_name="Escopo de Atividade",
                    ),
                ),
                (
                    "regional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes_veiculo",
                        to="cad_contrato.regional",
                        verbose_name="Regional",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atribuicoes",
                        to="veiculos.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atribuição de Veículo",
                "verbose_name_plural": "Atribuições de Veículos",
                "ordering": ["contrato", "regional", "escopo", "veiculo"],
                "unique_together": {("contrato", "veiculo", "regional", "escopo")},
            },
        ),
    ]
