# Generated by Django 5.1.6 on 2025-08-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="valor_locacao",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Valor de Locação Mensal (R$)",
            ),
        ),
    ]
