# Generated by Django 5.1.6 on 2025-08-17 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0002_veiculo_valor_locacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veiculo",
            name="km_por_mes",
        ),
    ]
