# Generated by Django 5.1.6 on 2025-03-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cad_contrato", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Funcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "salario",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComposicaoEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_equipes",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "quantidade_funcionarios",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("periculosidade", models.BooleanField(default=False)),
                ("horas_extras_50", models.PositiveIntegerField(default=0)),
                ("horas_extras_70", models.PositiveIntegerField(default=0)),
                ("horas_extras_100", models.PositiveIntegerField(default=0)),
                ("horas_sobreaviso", models.PositiveIntegerField(default=0)),
                ("horas_adicional_noturno", models.PositiveIntegerField(default=0)),
                (
                    "outros_custos",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cad_contrato.contractconfiguration",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro_equipe.equipe",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro_equipe.funcao",
                    ),
                ),
            ],
        ),
    ]
