# Generated by Django 5.1.6 on 2025-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
        ("cadastro_equipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="equipe",
            unique_together={("contrato", "nome")},
        ),
    ]
