# Generated by Django 5.1.6 on 2025-08-17 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_equipe", "0001_initial"),
        ("veiculos", "0003_remove_veiculo_km_por_mes"),
    ]

    operations = [
        migrations.AddField(
            model_name="composicaoequipe",
            name="km_rodado",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="KM Rodados por Mês",
            ),
        ),
        migrations.AddField(
            model_name="composicaoequipe",
            name="modalidade_veiculo",
            field=models.CharField(
                blank=True,
                choices=[("LOCADO", "Locado"), ("PROPRIO", "Próprio")],
                max_length=10,
                null=True,
                verbose_name="Modalidade do Veículo",
            ),
        ),
        migrations.AddField(
            model_name="composicaoequipe",
            name="quantidade_veiculos",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Quantidade de Veículos",
            ),
        ),
        migrations.AddField(
            model_name="composicaoequipe",
            name="veiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="veiculos.veiculo",
                verbose_name="Tipo de Veículo",
            ),
        ),
    ]
