# Generated by Django 5.1.6 on 2025-04-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_equipe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="funcaoequipe",
            name="horas_extras_70",
        ),
        migrations.AddField(
            model_name="funcaoequipe",
            name="horas_prontidao",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas de Prontidão (2/3)"
            ),
        ),
        migrations.AlterField(
            model_name="funcaoequipe",
            name="horas_adicional_noturno",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas Adicional Noturno"
            ),
        ),
        migrations.AlterField(
            model_name="funcaoequipe",
            name="horas_extras_100",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas Extras 100%"
            ),
        ),
        migrations.AlterField(
            model_name="funcaoequipe",
            name="horas_extras_50",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas Extras 50%"
            ),
        ),
        migrations.AlterField(
            model_name="funcaoequipe",
            name="horas_sobreaviso",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Horas de Sobreaviso (1/3)"
            ),
        ),
        migrations.AlterField(
            model_name="funcaoequipe",
            name="outros_custos",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Outros Custos",
            ),
        ),
        migrations.AlterField(
            model_name="funcaoequipe",
            name="periculosidade",
            field=models.BooleanField(default=False, verbose_name="Periculosidade"),
        ),
    ]
