# Generated by Django 5.1.6 on 2025-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_equipe", "0002_alter_equipe_nome_alter_equipe_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="descricao",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Descrição breve"
            ),
        ),
    ]
