# Generated by Django 5.1.6 on 2025-07-27 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
        ("cadastro_equipe", "0003_equipe_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipes",
                to="cad_contrato.cadastrocontrato",
            ),
        ),
    ]
