# Generated by Django 5.1.6 on 2025-04-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastrocontrato",
            name="status_contrato",
            field=models.CharField(
                choices=[
                    ("EM_LICITACAO", "Em Licitação"),
                    ("EM_RENOVACAO", "Em Renovação"),
                    ("ATIVO", "Ativo"),
                    ("ENCERRADO", "Encerrado"),
                ],
                default="EM_LICITACAO",
                max_length=15,
                verbose_name="Status do Contrato",
            ),
        ),
    ]
