# Generated by Django 5.1.6 on 2025-08-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="regional",
            unique_together={("contrato", "nome", "municipio")},
        ),
    ]
