# Generated by Django 5.1.6 on 2025-07-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cad_contrato", "0001_initial"),
        ("cadastro_equipe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustoDireto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custo_direto",
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustoDiretoFuncao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_funcionarios", models.PositiveIntegerField(default=1)),
                (
                    "quantidade_total_funcionarios",
                    models.PositiveIntegerField(default=0),
                ),
                ("salario_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "adicional_periculosidade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_horas_extras_50",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_horas_extras_100",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_adicional_noturno",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_prontidao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_sobreaviso",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "outros_custos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "beneficios",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "percentual_grupo_a",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "percentual_grupo_b",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "percentual_grupo_c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "percentual_grupo_d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "percentual_grupo_e",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "valor_grupo_a",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_grupo_b",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_grupo_c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_grupo_d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "valor_total_encargos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "custo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "composicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos_diretos",
                        to="cadastro_equipe.composicaoequipe",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos_diretos_funcoes",
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
                (
                    "escopo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastro_equipe.escopoatividade",
                    ),
                ),
                (
                    "funcao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custos_diretos",
                        to="cadastro_equipe.funcao",
                    ),
                ),
                (
                    "regional",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cad_contrato.regional",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contrato", "composicao", "funcao"),
                        name="unique_custo_por_funcao",
                    )
                ],
            },
        ),
    ]
