# Generated by Django 5.1.6 on 2025-08-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0002_alter_regional_unique_together"),
        ("custo_direto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_combustivel",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Custo de Combustível",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_despesas_diversas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Custo Despesas Diversas",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_despesas_ti",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Custo Despesas TI",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_epc",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Custo EPC"
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_epi",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Custo EPI"
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_equipamentos_ti",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Custo Equipamentos TI",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_ferramentas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Custo Ferramentas",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_materiais_consumo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Custo Materiais de Consumo",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="custo_veiculos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Custo de Veículos",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="km_rodado_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="KM Rodados Total",
            ),
        ),
        migrations.CreateModel(
            name="ConsolidacaoCustoContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custo_mao_obra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Mão de Obra",
                    ),
                ),
                (
                    "custo_veiculos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Veículos",
                    ),
                ),
                (
                    "custo_combustivel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Combustível",
                    ),
                ),
                (
                    "custo_equipamentos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Equipamentos",
                    ),
                ),
                (
                    "custo_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Total",
                    ),
                ),
                (
                    "custo_epi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo EPI",
                    ),
                ),
                (
                    "custo_epc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo EPC",
                    ),
                ),
                (
                    "custo_ferramentas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Ferramentas",
                    ),
                ),
                (
                    "custo_equipamentos_ti",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Equipamentos TI",
                    ),
                ),
                (
                    "custo_despesas_ti",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Despesas TI",
                    ),
                ),
                (
                    "custo_materiais_consumo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Materiais de Consumo",
                    ),
                ),
                (
                    "custo_despesas_diversas",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Custo Despesas Diversas",
                    ),
                ),
                (
                    "total_funcionarios",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Funcionários"
                    ),
                ),
                (
                    "total_equipes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total de Equipes",
                    ),
                ),
                (
                    "total_veiculos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total de Veículos",
                    ),
                ),
                (
                    "data_consolidacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da Consolidação"
                    ),
                ),
                (
                    "versao_calculo",
                    models.CharField(
                        default="1.0", max_length=10, verbose_name="Versão do Cálculo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidacao_custos",
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidação de Custos por Contrato",
                "verbose_name_plural": "Consolidações de Custos por Contrato",
                "ordering": ["-data_consolidacao"],
            },
        ),
        migrations.CreateModel(
            name="ConsolidacaoCustoPeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_periodo",
                    models.CharField(
                        choices=[
                            ("MENSAL", "Mensal"),
                            ("TRIMESTRAL", "Trimestral"),
                            ("ANUAL", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
                ("mes", models.PositiveIntegerField(blank=True, null=True)),
                ("trimestre", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "custo_mao_obra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_veiculos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_combustivel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_equipamentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("data_consolidacao", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidacoes_periodo",
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidação de Custos por Período",
                "verbose_name_plural": "Consolidações de Custos por Período",
                "ordering": ["-ano", "-mes", "-trimestre"],
                "unique_together": {
                    ("contrato", "tipo_periodo", "ano", "mes", "trimestre")
                },
            },
        ),
        migrations.CreateModel(
            name="ConsolidacaoCustoRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custo_mao_obra",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_veiculos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_combustivel",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_equipamentos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "custo_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("total_funcionarios", models.PositiveIntegerField(default=0)),
                (
                    "total_equipes",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("data_consolidacao", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidacoes_regionais",
                        to="cad_contrato.cadastrocontrato",
                    ),
                ),
                (
                    "regional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidacoes_custos",
                        to="cad_contrato.regional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consolidação de Custos por Regional",
                "verbose_name_plural": "Consolidações de Custos por Regional",
                "ordering": ["contrato", "regional__nome"],
                "unique_together": {("contrato", "regional")},
            },
        ),
    ]
