# Generated by Django 5.1.6 on 2025-06-29 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
        ("cadastro_equipe", "0001_initial"),
        ("custo_direto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="custodiretofuncao",
            name="unique_custo_por_funcao",
        ),
        migrations.RenameField(
            model_name="custodiretofuncao",
            old_name="valor_grupo_a",
            new_name="custo_por_funcionario",
        ),
        migrations.AlterUniqueTogether(
            name="custodiretofuncao",
            unique_together={("contrato", "composicao", "funcao")},
        ),
        migrations.AlterField(
            model_name="custodireto",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cad_contrato.cadastrocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="custodireto",
            name="custo_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="adicional_periculosidade",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="beneficios",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="composicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro_equipe.composicaoequipe",
            ),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cad_contrato.cadastrocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="custo_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="funcao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastro_equipe.funcao"
            ),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="outros_custos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="quantidade_funcionarios",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="salario_base",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_adicional_noturno",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_horas_extras_100",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_horas_extras_50",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_prontidao",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_sobreaviso",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_total_encargos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="escopo",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="percentual_grupo_a",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="percentual_grupo_b",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="percentual_grupo_c",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="percentual_grupo_d",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="percentual_grupo_e",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="regional",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="valor_grupo_b",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="valor_grupo_c",
        ),
        migrations.RemoveField(
            model_name="custodiretofuncao",
            name="valor_grupo_d",
        ),
    ]
