# Generated by Django 5.1.6 on 2025-05-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custo_direto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custodiretofuncao",
            name="quantidade_total_funcionarios",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
