# Generated by Django 5.1.6 on 2025-06-30 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cad_contrato", "0001_initial"),
        ("cadastro_equipe", "0001_initial"),
        (
            "custo_direto",
            "0002_remove_custodiretofuncao_unique_custo_por_funcao_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="custodiretofuncao",
            old_name="custo_por_funcionario",
            new_name="valor_grupo_a",
        ),
        migrations.AlterUniqueTogether(
            name="custodiretofuncao",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="escopo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro_equipe.escopoatividade",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="percentual_grupo_a",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="percentual_grupo_b",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="percentual_grupo_c",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="percentual_grupo_d",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="percentual_grupo_e",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="regional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cad_contrato.regional",
            ),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="valor_grupo_b",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="valor_grupo_c",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="custodiretofuncao",
            name="valor_grupo_d",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodireto",
            name="contrato",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custo_direto",
                to="cad_contrato.cadastrocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="custodireto",
            name="custo_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="adicional_periculosidade",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="beneficios",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="composicao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custos_diretos",
                to="cadastro_equipe.composicaoequipe",
            ),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custos_diretos_funcoes",
                to="cad_contrato.cadastrocontrato",
            ),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="custo_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="funcao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="custos_diretos",
                to="cadastro_equipe.funcao",
            ),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="outros_custos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="quantidade_funcionarios",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="salario_base",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_adicional_noturno",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_horas_extras_100",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_horas_extras_50",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_prontidao",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_sobreaviso",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="custodiretofuncao",
            name="valor_total_encargos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name="custodiretofuncao",
            constraint=models.UniqueConstraint(
                fields=("contrato", "composicao", "funcao"),
                name="unique_custo_por_funcao",
            ),
        ),
    ]
